  services:
    app:
      container_name: employee_import_app
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      working_dir: /var/www
      volumes:
        - ./src:/var/www
      ports:
        - "8000:8000"
        - "5173:5173"
      depends_on:
        - mysql
      command: php artisan serve --host=0.0.0.0 --port=8000

    mysql:
      image: mysql:8.0
      container_name: employee_import_db
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql

  volumes:
    mysql_data:
